version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
        # These are peer deps of Cargo and should not be automatically bumped
        - dependency-name: "semver"
        - dependency-name: "crates-io"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore
      include: scope
